version: '3.8'

services:
  # Main Football Platform
  app:
    build: .
    container_name: football-app
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    depends_on:
      - mlflow-server
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./metrics:/app/metrics
      - ./mlruns:/app/mlruns

  # MLflow Tracking Server & UI
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: mlflow-dashboard
    ports:
      - "5050:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    command: >
      sh -c "mlflow db upgrade sqlite:///app/mlflow.db && mlflow server --backend-store-uri sqlite:///app/mlflow.db --default-artifact-root /app/mlruns/ --host 0.0.0.0"
